name: meqtrack
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.4.0
  - r-renv
  - pandoc>=3.0
  - r-optparse
  - r-data.table
  - r-yaml
  - r-stringr
  - libcurl
  - openssl
  - libxml2
  - zlib
  - r-devtools
  - r-biocmanager
